### PR TITLE
Removed RateLimit for Lydia

### PR DESCRIPTION
**Pull request by Netkas**

### CODE REVIEW

**Comment by peaktogoo** [comment]
that's nice

**Comment by Netkas** [comment]
> that's nice

When a random person messages you and the AI responds only for every 2 messages. It seems odd and out of place. I prefer it where it would actually have conversations with people i don't want to talk to since i'm that antisocial.

**Comment by peaktogoo** [comment]
Yeah i know how lydia work.

**Comment by mdelahozl** [comment]
@peaktogoo Enable an option to eventually disable ratelimiting.

**Comment by peaktogoo** [comment]
> @peaktogoo Enable an option to eventually disable ratelimiting.

Express what you're trying to say more please?

**Comment by Netkas** [comment]
Yes, an option to enable or disable this feature instead of completely removing it would be ideal.

**Comment by peaktogoo** [comment]
@Netkas Alright, Not hard to do

**Comment by penn5** [comment]
But why? Earlier you opened an issue for this

**Comment by Netkas** [comment]
> But why? Earlier you opened an issue for this

This wasn't an issue, the issue was with official telegram bots. Whenever you used a official telegram bot, the AI would respond and enter "incorrect commands". sometimes, people don't even notice this and the bot would continue to respond. This causes the AI and Telegram Bot to spam each other back and forth causing more than 1k (greater at most cases) requests which consisted of the same input. essentially spam. 

For clarification; This isn't an issue when the AI does what it's intended to do. **Which is talk to users**, therefore there was no need to rate limit it per every two messages.

Even though this does not violate the usage conditions of the API, it will result in users being limited until they make a request to reverse this limitation. I've explained this before.

**Comment by Netkas** [comment]
I also fail to see the purpose of having a chat bot AI respond to Telegram Bots in the first place.

**Pull request merged**
